title: Codification Static
description: Struggle with the topic of codification!
theme: just-the-docs

url: https://LeBerek.github.io/Codification-static

aux_links:
  Template Repository: https://github.com/Leberek/Codification-static
